object Form1: TForm1
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  Caption = 'Form1'
  ClientHeight = 473
  ClientWidth = 438
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -30
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poMainFormCenter
  OnShow = UmClick
  PixelsPerInch = 96
  TextHeight = 36
  object Um: TButton
    Left = 8
    Top = 117
    Width = 97
    Height = 65
    Caption = '1'
    TabOrder = 0
    OnClick = UmClick
  end
  object Dois: TButton
    Left = 111
    Top = 117
    Width = 98
    Height = 65
    Caption = '2'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -30
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    OnClick = UmClick
  end
  object Tres: TButton
    Left = 215
    Top = 117
    Width = 98
    Height = 65
    Caption = '3'
    TabOrder = 2
    OnClick = UmClick
  end
  object Quatro: TButton
    Left = 8
    Top = 188
    Width = 97
    Height = 65
    Caption = '4'
    TabOrder = 3
    OnClick = UmClick
  end
  object Cinco: TButton
    Left = 111
    Top = 188
    Width = 98
    Height = 65
    Caption = '5'
    TabOrder = 4
    OnClick = UmClick
  end
  object Seis: TButton
    Left = 215
    Top = 188
    Width = 98
    Height = 65
    Caption = '6'
    TabOrder = 5
    OnClick = UmClick
  end
  object Sete: TButton
    Left = 8
    Top = 259
    Width = 97
    Height = 65
    Caption = '7'
    TabOrder = 6
    OnClick = UmClick
  end
  object Oito: TButton
    Left = 111
    Top = 259
    Width = 98
    Height = 65
    Caption = '8'
    TabOrder = 7
    OnClick = UmClick
  end
  object Nove: TButton
    Left = 215
    Top = 259
    Width = 98
    Height = 65
    Caption = '9'
    TabOrder = 8
    OnClick = UmClick
  end
  object Zero: TButton
    Left = 111
    Top = 330
    Width = 98
    Height = 65
    Caption = '0'
    TabOrder = 9
    OnClick = UmClick
  end
  object Virgula: TButton
    Left = 111
    Top = 401
    Width = 98
    Height = 65
    Caption = ','
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -30
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 10
    OnClick = VirgulaClick
  end
  object Mais: TButton
    Left = 8
    Top = 330
    Width = 97
    Height = 65
    Caption = '+'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -30
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 11
    OnClick = MaisClick
  end
  object Menos: TButton
    Left = 215
    Top = 330
    Width = 98
    Height = 65
    Caption = '-'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -30
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 12
    OnClick = MenosClick
  end
  object Multiplicar: TButton
    Left = 8
    Top = 401
    Width = 97
    Height = 65
    Caption = '*'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -30
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 13
    OnClick = MultiplicarClick
  end
  object Dividir: TButton
    Left = 215
    Top = 401
    Width = 98
    Height = 65
    Caption = '/'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -30
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 14
    OnClick = DividirClick
  end
  object Igual: TButton
    Left = 328
    Top = 117
    Width = 104
    Height = 173
    Caption = '='
    TabOrder = 15
    OnClick = IgualClick
  end
  object lLimpar: TButton
    Left = 328
    Top = 296
    Width = 104
    Height = 170
    Caption = 'C'
    TabOrder = 16
    OnClick = lLimparClick
  end
  object Visor: TEdit
    Left = 8
    Top = 8
    Width = 424
    Height = 96
    Alignment = taRightJustify
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -73
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 17
  end
end
